### ISSUE TITLE
VERTX JUNIT5 Issue Mocking Static Classes

### ISSUE THREAD

**Issue by DMIC123** [eclipse-vertx/vertx-junit5#124]
I am unable to mock static classes for Vertx JUNIT5. Added all dependencies as well in pom.xml for Vertx JUNIT5. (junit-jupiter-api,junit-jupiter-engine,mockito-inline,mockito-core,mockito-junit-jupiter,vertx-junit5)

Code Snippet:

@ExtendWith (VertxExtension.class) 
VertxTestClass {

    @BeforeEach
     public void beforeEach(Vertx vertx,VertxTestContext ctx)
    { 
        vertx=Vertx.vertx(options);
        Mockito.mockstatic(Placeholder.java);
        when (Placeholder.getValue(Mockito.anyString()).thenReturn("value")
        vertx.deployVerticle(MyVerticle.class.getaName()).onSuccess(ok->ctx.completeNow())
    }

}

Main Class: 

MyVerticle extends AbstractVerticle{

    @Override
 public void start(Promise<Void> appState)
    { …. 
     
          Placeholder.getValue(“MyValue”);  // this is always returning NULL even this is mocked in test class
        … 
    }

}

When verticle is deployed the start method MyVerticle Class is invoked. But even though Placeholder class is mocked then also Placeholder.getValue("MyValue") is returned as NULL.

Unable to figure out how to do that mocking. I have tried with Mocked Static as well but that also does not help. To me it looks like when vertx deploy verticle is called then the start method is not being invoked directly but it will be invoked by Vertx. so somewhere that scope is lost and whatever mocking is done in test class is lost. Unable to figure out a way. Any help is appreciated

**Comment by DMIC123** [comment]
vertx-junit5 version is 4.3.7, mockito-inline is 3.8.0,junit-jupiter-api is 5.8.2,mockito-junit-jupiter is 2.23.0

**Comment by tsegismont** [comment]
This does not look like a bug but rather a question about Mockito static mocking. I'm not sure this is the best place to ask for help about it.

Perhaps if you modify your snippets to show an easily reproducible case someone will try it out.

**Comment by DMIC123** [comment]
I have mentioned the above steps . Unable to figure out a way . Earlier with JUNIT4 we could easily mock such scenarios with PowerMockito.
