### ISSUE TITLE
Configuring Vertx instances with real environment variable and Java system property

### ISSUE THREAD

**Issue by rotscher** [eclipse-vertx/vertx-junit5#125]
For [configuring vert.x instances](https://vertx.io/docs/vertx-junit5/java/#_configuring_vertx_instances) an environment variable named `vertx.parameter.filename` can be set. This works on some environments but not on all. I tested successfully in IDE, with Maven on Red Hat and Windows, but it does not work in a CI Pipeline running on Debian. 

As environment variables are normally written (and supported?) with capital letters and underscores, why not supporting this feature in the following manner:

1. Read Java system property named `vertx.parameter.filename`
2. If no system property set, read environment variable named `VERTX_PARAMETER_FILENAME`
3. If no environment variable set, then no configuration is loaded

This would open more configuration options which are well known and work on all platforms.

If there is a chance that this feature is accepted, I would be willing to make a PR.

**Comment by tsegismont** [comment]
What's the reason it doe not work in a CI pipeline running on Debian? Sounds odd.

**Comment by rotscher** [comment]
Yes, this sounds odd and I don't have an explanation. But why is the environment variable defined with lowercase characters and dots? This is unusal and often not supported especially the dots. Examples using Gitlab CI:

#### Variable in gitlab-ci.yml
```
variables:
  vertx.parameter.filename: src/test/resources/config.json
```

Aborts with `/bin/bash: line 115: export: vertx.parameter.filename=src/test/resources/config.json': not a valid identifier`

#### Exporting environment variable in script part

```yaml
stages:
  - build
  script:
    - export vertx.parameter.filename="src/test/resources/config.json"
```

Same error: `/usr/bin/bash: line 170: export: vertx.parameter.filename=src/test/resources/config.json': not a valid identifier`

**Comment by rotscher** [comment]
Yes, I use an environment variable as described in the [documentation](https://vertx.io/docs/vertx-junit5/java/#_configuring_vertx_instances): 

> 2. create an environment variable vertx.parameter.filename pointing to that file

And the documentation matches with the implementation `System.getenv(VERTX_PARAMETER_FILENAME);`. To me, defining a system property does not help.

**Comment by tsegismont** [comment]
My bad, I misread the documentation.

Reading the [standard definition document](https://pubs.opengroup.org/onlinepubs/7908799/xbd/envvar.html), applications should tolerate any character from the portable character set, but in practice not every app does.

For example, here's what I see in my terminal:

```
$ env "vertx.parameter.filename=src/test/resources/config.json" bash -c 'env' | grep vertx
vertx.parameter.filename=src/test/resources/config.json

$ export vertx.parameter.filename="src/test/resources/config.json"
bash: export: `vertx.parameter.filename=src/test/resources/config.json': not a valid identifier
```

So I believe we should accept `vertx.parameter.filename` as sysprop and `VERTX_PARAMETER.FILENAME` as env var.
For backwards compatibility, we can continue to accept `vertx.parameter.filename` as env var on systems which support it.

Thank you @rotscher for this good report!
