### ISSUE TITLE
"@ExtendWith(VertxExtension.class)" annotations in examples don't seem to be necessary

### ISSUE THREAD

**Issue by d-william** [eclipse-vertx/vertx-junit5#135]
In [this](https://github.com/eclipse-vertx/vertx-junit5/blob/04e1b13897a195d46d892650880943290b3feeb2/src/main/java/examples/Examples.java#L72) examples files, some "@ ExtendWith(VertxExtension.class)" annotations don't seem to be necessary.

In ATest and in BTest, the Vertx instance is created manually.
In BTest, the VertxTestContext object is created in the test method
In these cases, VertxExtension is not used and remove the annotation does not change the behavior of examples.

**Comment by tsegismont** [comment]
Fixed by aad9ab9
